### ISSUE TITLE
One-off tasks against a dependent container

### ISSUE THREAD

**Issue by jagregory** [charleskorn/batect#105]
I have a service and a local S3 instance. I need to run an aws-cli command to create a bucket before my app can run. What I would like to do is:

- Launch the local S3
- Run aws-cli command to create a bucket
- Launch my local server

How I’ve attempted it:

```yaml
containers:
  s3: ...
  aws-cli: ...
  service: ...

tasks:
  start:
    container: service
    dependencies:
      - s3
    prerequisites:
      - createS3Bucket
   
  createS3Bucket:
    container: aws-cli
    run:
      command: aws s3 mb s3://example
```

This doesn't work because the prerequisites are executed before the task's dependencies are started.

Then I tried adding the S3 container as a dependency to the `createS3Bucket` task:

```yaml
containers:
  s3: ...
  aws-cli: ...
  service: ...

tasks:
  start:
    container: service
    dependencies:
      - s3
    prerequisites:
      - createS3Bucket
   
  createS3Bucket:
    container: aws-cli
    dependencies:
      - s3
    run:
      command: aws s3 mb s3://example
```

This also doesn't work, because when `createS3Bucket` is complete it tears down the `s3` container, and then `start` spins up a new one.

It'd be great if Batect had a way to model this flow.

**Comment by charleskorn** [comment]
Hey @jagregory, thanks for the suggestion. I agree that it would be great if batect could cover this situation.

I'm going to think about this a bit more before I commit to a solution. One idea I have is something like a `setup_commands` array on each container definition, so then it would look something like this:

```yaml
containers:
  s3:
    ...
    setup_commands:
      - aws s3 mb s3://example

  service: ...

tasks:
  start:
    container: service
    dependencies:
      - s3
```

The idea being that these commands would be run in the containers after they report as healthy but before any containers that depend on them start. Would something like that fit your use case? 

Or would you rather have the ability to run a command in another container as a setup step? I'm imagining something like init containers in Kubernetes. That would be significantly more complex but also much more powerful and flexible:

```yaml

tasks:
  start:
    container: service
    dependencies:
      - s3
    setup:
      - container: aws-cli
        command: aws s3 mb s3://example
```

In the meantime, to solve your problem now, you might be able to create the bucket at image build time and bake it into the image if your S3 mock saves things to disk. Or you could do something a bit hacky where you have a intermediary init container that depends on the S3 container and creates the bucket and then sleeps and reports as healthy, which the service container then depends on - the effect being that the service won't start until the initialisation is complete.
