### ISSUE TITLE
.dockerignore is incorrectly parsed

### ISSUE THREAD

**Issue by cazgp** [charleskorn/batect#113]
Given a `.dockerignore` file:

```
# Ignore everything
*

# But what docker actually needs
!.cache
!ci
!package.json
!requirements
!src
!typings
!yarn.lock
```

and a `batect` config:

```
...
    build_directory: .
    dockerfile: ci/server.dev.Dockerfile
    run_as_current_user:
        enabled: true
        home_directory: /home/code
    volumes:
        - container: /code/src
          local: src
          options: cached
    working_directory: /code
```

The error message:

```
Error: Could not build image from directory '...'.
Building image failed: Cannot locate specified Dockerfile: ci/server.dev.Dockerfile
```

Removing the `.dockerignore` file makes everything work.

I would try to debug the cause and make a PR but don't speak kotlin yet :(
