### ISSUE TITLE
Error message given when indentation in configuration file is incorrect is difficult to understand

### ISSUE THREAD

**Issue by charleskorn** [charleskorn/batect#17]
If you have a configuration file with incorrect indentation, such as:

```yaml
tasks:
  run:
    description: Run the application
      prerequisites: # This line shouldn't be indented, it should be at the same level as 'description'
      - setup
    run:
      container: build-env
      command: yarn start
```

then you get an error message like this:

```
/home/user/Repositories/project/batect.yml (line 27, column 18): mapping values are not allowed here
in 'reader', line 28, column 20:
          prerequisites:
                       ^
 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: mapping values are not allowed here
in 'reader', line 28, column 20:
          prerequisites:
                       ^
 
at [Source: (sun.nio.ch.ChannelInputStream); line: 28, column: 20]
at [Source: (sun.nio.ch.ChannelInputStream); line: 27, column: 18] (through reference chain: batect.config.io.ConfigurationFile["tasks"])
```

...which is not very clear at all. It would be better if it led the user to what the real issue is.
