### ISSUE TITLE
Received error message when trying to run a particular batect task after upgrading

### ISSUE THREAD

**Issue by Sami5** [charleskorn/batect#19]
I'm getting the following error when trying to run a particular batect task:

```bash
Test Suites: 15 passed, 15 total
Tests:       6 skipped, 91 passed, 97 total
Snapshots:   0 total
Time:        9.182s
Ran all test suites.

Clean up: done

Running unit-test...
build-env: running true

Error: Could not run container build-env.
Resizing TTY for container '0d60dfbf9a42a41342b51152a8376f67f1f8c20aa834fc561a436de4fd3daadd' failed: cannot resize a stopped container: unknown

Clean up: done

The task unit-test failed. See above for details.
```
The above unit test ran but I got an error at the end

I'm finding that tasks which do not include a ``prerequisite`` property will work fine but ones that do, will not. For example this works:

```yml
unit-test-ui:
    description: Run unit tests for UI
    run:
      container: build-env
      command: scripts/unit-test.sh
```

But this does not:

```yml
unit-test:
    description: Run all unit tests for both UI and BFF
    prerequisites:
      - unit-test-backend
      - unit-test-ui
    run:
      container: build-env
      command: "true"
```
