### ISSUE TITLE
Support for using environment variables in volume paths

### ISSUE THREAD

**Issue by wandrewni** [charleskorn/batect#223]
Our organization uses maven as our primary build tool, which puts the repository for downloaded dependencies in `$HOME/.m2/repository`.  We would like to be able to mount that directory into the build container's maven repository, but as the `local` field requires absolute paths, there is no portable way to specify a developers `$HOME/.m2/repository`

We would like to do something like:
```
      - local: $HOME/.m2/repository
        container: /home/container-user/.m2/repository
        options: cached
```

Can this feature be added? Or is there another way to accomplish this goal?

**Comment by charleskorn** [comment]
Hey @wandrewni, thanks for the question. You can use `~` to refer to the home directory when specifying the local path for a directory mount, so your example would look something like:

```yaml
      - local: ~/.m2/repository
        container: /home/container-user/.m2/repository
        options: cached
```
