### ISSUE TITLE
Image building fails on ADD step with remote source

### ISSUE THREAD

**Issue by alpha-er** [charleskorn/batect#270]
Trying out batect and it fails on building an image using a Dockerfile with an `ADD` step with a remote source.

Dockerfile:
```
ARG BASE_VERSION
FROM <redacted_docker_registry_repo>:${BASE_VERSION}

# Security check
ADD --chown=app:app https://get.sensiolabs.org/security-checker.phar security-checker.phar
RUN php security-checker.phar security:check composer.lock; exit 0
```

batect.yml:
```
containers:
  app:
    dockerfile: Dockerfile
    build_directory: .
    build_args:
      BASE_VERSION: latest

tasks:
  build:
    description: build
    run:
      container: app
      command: echo 'test'
```
Running the batect command:
```
→ ./batect build
Running build...
app: building image: step 3 of 4: ADD --chown=app:app https://get.sensiolabs.org/security-checker.phar security-checker.phar

Error: An unexpected exception occurred during execution.
During execution of step of kind 'BuildImageStep': java.util.NoSuchElementException: Key id is missing in the map.

Clean up: done

The task build failed. See above for details.
```

batect version:
```
→ ./batect --version
batect version:    0.37.1
Built:             2019-10-10 10:31:41 +0000
Built from commit: b7623f4d0d1b1c781e3e377393670cfcb19882b3 (commit date: 2019-10-10 20:47:21 +1100)
JVM version:       Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_131
OS version:        Mac OS X 10.14.3 (x86_64)
Docker version:    19.3.2 (API version: 1.40, minimum supported API version: 1.12, commit: 6a30dfc)

For documentation and further information on batect, visit https://github.com/charleskorn/batect.
```
