### ISSUE TITLE
Blank environment variable values cause exception

### ISSUE THREAD

**Issue by alexswilliams** [charleskorn/batect#340]
It appears that including an environment variable with a blank value (a valid thing to do in some situations) causes a spec checking error.

e.g. the following task:
```
tasks:
  myTask:
    run:
      container: some-container
      command: sh -c 'echo "hi!"'
      environment:
        SOME_ENV_VAR: ""
```
will produce the following error: `Invalid expression ''` when running `./batect myTask`

Changing to `SOME_ENV_VAR: "N/A"` causes the app to run as expected, but causes the value `N/A` to be injected into the environment instead of an empty string.
