### ISSUE TITLE
Example of customising shell inside container

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#39]
What a keen tool, love it, thank you.

Some documentation requests:
- Help setting up the first time shell (`command: bash`).  For example, explaining how to bring in a user's `.bashrc`, `.bash_profile`, etc.
- Tips on integrating common shell setups, such as one of the fabulous "git" prompts.  https://github.com/magicmonty/bash-git-prompt is a popular example

I'm starting a new project for client, and look forward to suggesting batect to the teams.

**Comment by charleskorn** [comment]
I'm a little unclear on your first question - are you asking how to bring in your `.bashrc` or `.bash_profile` into a container?

**Comment by binkley** [comment]
This may be user inexperience at play.  When I pop open a shell in the image, I'd like my bash experience to match that when I'm not using docker, eg, shell prompt and all that.  I'm not sure the exact level of developer your docs are aimed at.  For an experienced docker user, they probably know what to do; perhaps a good link in your docs pointing to getting for someone like me.

**Comment by charleskorn** [comment]
That's certainly possible, but does go against the idea of batect a little - one of the main ideas is to provide everyone with a consistent environment (to remove "works on my machine" issues), so incorporating each user's profile breaks that consistency. 

However, if you're happy to live with that compromise, doing it is straightforward. In the definition of the container, add something like this:

```yaml
containers:
  build-env:
    image: my-cool-build-env
    volumes:
      - local: ~/.bash_profile
        container: /home/container-user/.bash_profile # or /root/.bash_profile if you're not using run_as_current_user
        options: ro # So you don't accidentally change your global .bash_profile from within the container
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```

For your second question, it's very setup-specific. If you're not using `run_as_current_user`, then you can add the installation instructions in the [bash-git-prompt readme](https://github.com/magicmonty/bash-git-prompt) to your Dockerfile, keeping in mind that you'll be root inside the container and so need to edit `/root/.bashrc` / `/root/.bash_profile`. 

If you are using `run_as_current_user`, you'll need to create a little [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) script that adds the snippet to `~/.bashrc` / `~/.bash_profile` when the container starts and then starts your chosen shell. (You can't do this at image build time because the user's home directory is only created when the container starts.)

Hope that all makes sense, please let me know if you have any further questions or need any clarification. (Once you're happy with the answers here, I'll tidy them up and put them in the documentation itself, like you originally suggested.)

**Comment by charleskorn** [comment]
(please ignore the referenced commit above, that was meant to refer to #41)

**Comment by charleskorn** [comment]
That's certainly possible, but does go against the idea of batect a little - one of the main ideas is to provide everyone with a consistent environment (to remove "works on my machine" issues), so incorporating each user's profile breaks that consistency. 

However, if you're happy to live with that compromise, doing it is straightforward. In the definition of the container, add something like this:

```yaml
containers:
  build-env:
    image: my-cool-build-env
    volumes:
      - local: ~/.bash_profile
        container: /home/container-user/.bash_profile # or /root/.bash_profile if you're not using run_as_current_user
        options: ro # So you don't accidentally change your global .bash_profile from within the container
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```

For your second question, it's very setup-specific. If you're not using `run_as_current_user`, then you can add the installation instructions in the [bash-git-prompt readme](https://github.com/magicmonty/bash-git-prompt) to your Dockerfile, keeping in mind that you'll be root inside the container and so need to edit `/root/.bashrc` / `/root/.bash_profile`. 

If you are using `run_as_current_user`, you'll need to create a little [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) script that adds the snippet to `~/.bashrc` / `~/.bash_profile` when the container starts and then starts your chosen shell. (You can't do this at image build time because the user's home directory is only created when the container starts.)

Hope that all makes sense, please let me know if you have any further questions or need any clarification. (Once you're happy with the answers here, I'll tidy them up and put them in the documentation itself, like you originally suggested.)
