### ISSUE TITLE
Improve the error message when defining empty containers/tasks

### ISSUE THREAD

**Issue by pameck** [charleskorn/batect#4]
When defining a container with an empty property (`nodejs`), I get the following error message :

```
my-project/batect.yml: Could not load configuration file: null
Caused by: java.lang.NullPointerException
```

Here is my `batect.yaml`: 

```
project_name: my-project

containers:
  nodejs:

tasks:
  start:
    run:
      container: nodejs
      command: ./go.sh
```

It also happens for empty tasks (`start`):

```
project_name: my-project

containers:
  nodejs:
    build_directory: nodejs

tasks:
  start:
```
