### ISSUE TITLE
Exiting Docker shell failed

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#46]
Using batect 0.24.0.  Upgraded from 0.23.0 by copying a newer shell script version over the older one.  This task:
```
tasks:
    shell:
        run:
            container: build-env
            command: bash --login
```
Produced this error when exiting:
```
build-env: running bash --login

boxley@build-env:/src$ exit
logout

Error: An unexpected exception occurred during execution.
java.lang.RuntimeException: Invoking 'stty 6b02:3:4b00:200005cb:4:ff:ff:7f:17:15:12:ff:3:1c:1a:19:11:13:16:f:1:0:14:ff' failed with exit code 1: stty: 'standard input': unable to perform all requested operations

Clean up: done

The task shell failed. See above for details.
```
