### ISSUE TITLE
Behaviour of command without shell entrypoint is unexpected

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#52]
I've tried several YAML variations on quoting multi-line strings.  Latest is:
```
    run:
      container: build-env
      command: './gradlew assemble
            && java -jar build/libs/docker-java11-0.0.1-SNAPSHOT.jar'
```
In each case, batect complains:
```
Task '&&' not found in root project 'docker-java11'.
```
I'm sure this is PEBKAC.  What am I doing wrong?

**Comment by binkley** [comment]
I'm not sure this is a multiline issue.  I was trying YAML multiline options from: https://yaml-multiline.info/

When I tried using a single-line, single-quoted string, I still had the same complaint:
```
  run:
    run:
      container: build-env
      command: './gradlew assemble && java -jar build/libs/docker-java11-0.0.1-SNAPSHOT.jar'
```
