### ISSUE TITLE
Project level environment variables

### ISSUE THREAD

**Issue by marty-macfly** [charleskorn/batect#58]
Hello,

We can define default variables on container and task with the use of `${MY_VAR:-default_value}`. In my case I use the variable at two different places like that:

```
project_name: test

containers:
  build:
    build_directory: .
    environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_DATABASE: ${DB_DATABASE:-test}
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_DATABASE:-test}
```

Would be easier to set the default value at project level instead of everytime i'm using it. Like that:

```
project_name: test
environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_DATABASE: ${DB_DATABASE:-test}

containers:
  build:
    build_directory: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
```

If they are not defined on the host env variable they will get the default value set at the top of the project and be used everywhere else with that value. Do you think that's an interesting feature ? Or may be there is already a way to doing it ?

**Comment by charleskorn** [comment]
Hi @marty-macfly, thanks for the suggestion. I think this makes a lot of sense, and I've been thinking about something similar myself.

It's already on the [roadmap](https://github.com/charleskorn/batect/blame/master/ROADMAP.md#L37), and I plan to implement it soon (for some definition of soon).

Having said that, if you're interested in submitting a PR I'd be very happy to discuss this in further detail before you start and review it as you go. Otherwise, please watch this space :)

**Comment by charleskorn** [comment]
Hi @marty-macfly, thanks again for your feedback. I've just added support for YAML aliases and anchors, which should make it easy to do things like this, and it will be part of v0.27 (which I'm planning to release soon). 

You can now do something like this:

```yaml
project_name: test

.db-environment: &db-environment
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_DATABASE: ${DB_DATABASE:-test}

containers:
  build:
    build_directory: .
    environment: *db-environment
  db:
    image: postgres:9.6
    environment: *db-environment
```

You can also use a similar technique for individual values if you don't want to share the entire set of environment variables, or if you want to customise the environment for either container (or combine different sets of configuration), take a look at the merge operator (`<<`) - there will be more examples of this on the [configuration docs page](https://batect.charleskorn.com/config/Overview.html) once I push out the release later today.
