### ISSUE TITLE
Extremely poor performance compared to docker-compose

### ISSUE THREAD

**Issue by nesl247** [charleskorn/batect#99]
I'm not sure what the cause of this is, but if I run `phpunit` in `batect`, it takes `3.84 minutes` compared to `6.1 seconds` in `docker-compose`. This is not including the build time for the containers, only the time taken by phpunit itself (it outputs it at the end of the tests).

Both of them are not using any volume mounts, and are using the same `Dockerfile`.

**Comment by charleskorn** [comment]
Hi @nesl247, thanks for your feedback. That doesn't sound right at all, execution performance should be on par with docker-compose. 

Are you able to share a sample project that reproduces the problem so that I can investigate further? And could you please post the output from `./batect --version`?

**Comment by nesl247** [comment]
Hey. Unfortunately I can't provide the current project as a sample, but I will try and dockerize something else and see if I can reproduce it. Until then, I've included the information request as well as other potentially relevant information.

```
batect version:    0.32
Built:             2019-05-19 09:19:58 +0000
Built from commit: f96aef904d105c6456f4a4b60f68bc3d87ae4845 (commit date: 2019-05-19 15:18:32 +1000)
JVM version:       Oracle Corporation OpenJDK 64-Bit Server VM 12.0.1
OS version:        Mac OS X 10.14.5 (x86_64)
Docker version:    18.9.2 (API version: 1.39, minimum supported API version: 1.12, commit: 6247962)

For documentation and further information on batect, visit https://github.com/charleskorn/batect.
```

```
docker-compose version 1.23.2, build 1110ad01
```

```yaml
project_name: shop-front

containers:
  php:
    build_directory: .
    dockerfile: docker/php/Dockerfile
    build_args:
      GITHUB_TOKEN: $GITHUB_TOKEN
    environment:
      LINIO_ENV: local
      XDEBUG_CONFIG: remote_host=host.docker.internal

tasks:
  unitTest:
    description: Run the unit tests.
    run:
      container: php
      command: vendor/bin/phpunit
```

```yaml
version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - GITHUB_TOKEN
    image: shop-front-php:${IMAGE_TAG:-latest}
```

`docker-compose run --rm php vendor/bin/phpunit`
